### ISSUE TITLE
CSS Functions

### ISSUE THREAD

**Issue by MZOG** [MZOG/MikaCars#11]
> Zadanie z hero przygotuję Ci jutro, tymczasem tutaj masz sporo ciekawych rzeczy z CSS'em.

https://css-tricks.com/complete-guide-to-css-functions/
Sporo nowych rzeczy się dowiesz czytając ten artykuł, zainteresuj się funkcją`var()`, która może Ci pomóc z ogarnianiem kolorów w CSS. Ustawiając `--primary: #fefefe;` możesz łatwo ustawiać kolory np. `color: var(--primary);`
Jest to przydatne, ponieważ w przypadku gdy chciałbyś zmienić główny kolor strony, to zmieniasz wartość `--primary` tylko w jednym miejscu.

No, poczytaj o tym i zmień w projekcie wszystkie kolory używając właśnie `var()`

**Comment by Loghart** [comment]
Dobrze pysiu :*
