### ISSUE TITLE
CSS: Position

### ISSUE THREAD

**Issue by MZOG** [MZOG/MikaCars#6]
Zrozumienie `position` w css to podstawa. Im szybciej ogarniesz jak działa `position: relative` albo `absolute`, tym szybciej zaczniesz tworzyć bardziej skomplikowane struktury w swoim layoucie.

Tutaj masz wszystko wyjaśnione:
https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by Loghart** [comment]
Wbijaj na przyczepę I odpalaaaaaaam

**Comment by MZOG** [comment]
CSS Position ogarnięte? Mogę zamknąć issue?

**Comment by Loghart** [comment]
Mysle, ze tak !
