### ISSUE TITLE
Nawigacja - wersja mobilna

### ISSUE THREAD

**Issue by MZOG** [MZOG/MikaCars#7]
Tworzenie strony wymaga czasem odpalenia kreatywnej części mózgu. 
Nawigacja mobilna będzie Twoim zdaniem, które stworzysz bez wersji graficznej 👍 

- Zobacz sobie jak wyglądają strony z nawigacją mobilną
- Stwórz nawigację mobilną, po lewej stronie chcę logo, po prawej na razie może być sam napis "MENU", które po kliknięciu otworzy nawigację mobilną. 
- Nawigacja ma "wjeżdżać" z prawej strony, ma mieć szerokość 100% aż do powiedzmy 450px.
- Powyżej 450px szerokości menu powinno zajmować 50% szerokości stron, aż do 768px.
- Od 768px aż do 992px szerokość rozwiniętego menu ma mieć 30% - 40%, zrób tak żeby wyglądało dobrze. 
- Od 992 nawigacja mobilna wraz z napisem MENU ma się schować i pojawić się normalna nawigacja, którą stworzyłeś.

**Comment by MZOG** [comment]
Ok, dziś zrobiliśmy wersję mobilną. Tam były małe niedociągnięcia z top-menu.

- Zmniejsz logo na urządzeniach mobilnych, powiedzmy do 992px niech będzie od 30/40px mniejsze, zobacz jak pasuje najlepiej, jak wciąż proporcjonalnie będzie zbyt duże to zmniejsz o więcej px.
- Odstęp od top-menu do nawigacji jest zbyt duży, wypadałoby zmniejszyć odstęp na urządzeniach mobilnych aż do 992px.
- Masz podstawy js'a więc możesz pomyśleć nad zmianą tekstu MENU na "X" jak nawigacja ma klasę `active`.

**Comment by Loghart** [comment]
*zrobiłeś
